### ISSUE TITLE
Missing Exports from Windows GNU Target

### ISSUE THREAD

**Issue by SBuercklin** [rust-cross/cargo-zigbuild#251]
When I compile the following `lib.rs` with the accompanying `Cargo.toml` for `x86_64-pc-windows-gnu`, the function `test_fn` is missing from the resulting DLL. However, this code compiles and exposes `test_fn` for `x86_64-unknown-linux-gnu, aarch64-apple-darwin`. 

I compile the code with `cargo zigbuild --release --target *insert_target*` using a slightly modified version of the `cargo-zigbuild` Docker image

source:
```rust
#[no_mangle]
pub extern "C" fn test_fn(tag_id_c: i32) -> i32 {
    return tag_id_c;
}
```

Cargo.toml:
```toml
[package]
name = "wincompile"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["cdylib"]
```
