### ISSUE TITLE
cargo-zigbuild fails in GH Action

### ISSUE THREAD

**Issue by sundaram123krishnan** [rust-cross/cargo-zigbuild#271]
This is my workflow file:
```yaml
  cross:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Add aarch64 target with rustup
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.9.1

      - name: Install cargo zigbuild
        run: cargo install cargo-zigbuild

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test for cross
        run: make cross-ci
 ```
It produces this error:
```sh
error: linking with `/home/runner/.cache/cargo-zigbuild/0.19.1/zigcc-aarch64-unknown-linux-gnu-8f83.sh` failed: exit status: 1
```
But works perfectly fine on my local machine (Arch linux)
